services:
    library:
      image: postgres:latest
      environment:
        POSTGRES_USER: superadmin
        POSTGRES_PASSWORD: superadmin
        POSTGRES_DB: library
      ports:
        - "5436:5432"
      volumes:
        - library_bd_data:/var/lib/postgresql/data
        - ./sql/library/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - less_5_network
volumes:
  library_bd_data:
    
networks:
  less_5_network:
      driver: bridge